-- @1 GROUP BY
SELECT PID, JMENO
FROM DBO.PREDMET
GROUP BY PID, JMENO
GO

/*SELECT PID, JMENO
FROM DBO.PREDMET;*/

-- @2 WHERE
SELECT *
FROM DBO.PREDMET
WHERE 1 = 1
GO

/*SELECT *
FROM DBO.PREDMET;*/

-- @3 WHERE
-- vnejsi podminky vs vnitrni podminky (maji jiny vyznam)
SELECT *
FROM DBO.STUDENT SDT
INNER JOIN DBO.STUDUJE SDE ON SDT.SID = SDE.SID
INNER JOIN DBO.PREDMET PDT ON SDE.PID = PDT.PID
WHERE SDT.SID = SDE.SID
ORDER BY SDT.SID
GO

/*SELECT *
FROM DBO.STUDENT SDT
INNER JOIN DBO.STUDUJE SDE ON SDT.SID = SDE.SID
INNER JOIN DBO.PREDMET PDT ON SDE.PID = PDT.PID
ORDER BY SDT.SID;*/

-- @4 JOIN
SELECT distinct SDT.SID, SDT.JMENO
FROM DBO.STUDENT SDT
LEFT JOIN DBO.STUDUJE SDE ON SDT.SID = SDE.SID
GO

/*SELECT SDT.SID, SDT.JMENO
FROM DBO.STUDENT SDT
;*/

-- @5 LIKE
SELECT *
FROM PREDMET
WHERE JMENO LIKE '%'
GO

/*SELECT *
FROM PREDMET;*/


